import { useState, useEffect } from 'react';
import ImageCard from '../components/ImageCard';
import GeometricBackground from '../components/GeometricBackground';

const API_URL = '/api';

const STYLES = [
  { key: 'all', label: 'All Styles' },
  { key: 'constructivist', label: 'Constructivist' },
  { key: 'suprematist', label: 'Suprematist' },
  { key: 'propaganda', label: 'Propaganda' },
  { key: 'industrial', label: 'Industrial' },
];

export default function Gallery() {
  const [images, setImages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeStyle, setActiveStyle] = useState('all');
  const [page, setPage] = useState(1);
  const [pagination, setPagination] = useState(null);

  useEffect(() => {
    fetchImages();
  }, [activeStyle, page]);

  async function fetchImages() {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page, limit: 20 });
      if (activeStyle !== 'all') params.set('style', activeStyle);

      const res = await fetch(`${API_URL}/images?${params}`);
      const data = await res.json();
      setImages(data.images);
      setPagination(data.pagination);
    } catch (err) {
      console.error('Failed to load gallery:', err);
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <GeometricBackground />
      <div className="page-content" style={{ position: 'relative', zIndex: 2 }}>
        <div className="container" style={{ paddingTop: 'var(--space-2xl)', paddingBottom: 'var(--space-2xl)' }}>
          <div className="section-header animate-in">
            <h2>Public <span className="text-red">Gallery</span></h2>
            <div className="section-divider"></div>
            <p>Explore constructivist art generated by the community</p>
          </div>

          {/* Style Filter */}
          <div className="filter-bar animate-in animate-in-delay-1" id="style-filter">
            {STYLES.map((s) => (
              <button
                key={s.key}
                className={`filter-btn ${activeStyle === s.key ? 'active' : ''}`}
                onClick={() => { setActiveStyle(s.key); setPage(1); }}
                id={`filter-${s.key}`}
              >
                {s.label}
              </button>
            ))}
          </div>

          {loading ? (
            <div style={{ display: 'flex', justifyContent: 'center', padding: 'var(--space-4xl)' }}>
              <div className="spinner"></div>
            </div>
          ) : images.length === 0 ? (
            <div className="empty-state animate-in">
              <div className="icon">🖼️</div>
              <h3>No Art Yet</h3>
              <p>Be the first to create something bold. Head to the Studio and generate your first piece.</p>
            </div>
          ) : (
            <>
              <div className="image-grid animate-in animate-in-delay-2">
                {images.map((image) => (
                  <ImageCard key={image.id} image={image} />
                ))}
              </div>

              {/* Pagination */}
              {pagination && pagination.pages > 1 && (
                <div style={{ display: 'flex', justifyContent: 'center', gap: 'var(--space-sm)', marginTop: 'var(--space-2xl)' }}>
                  <button
                    className="btn btn-ghost btn-sm"
                    disabled={page <= 1}
                    onClick={() => setPage(p => p - 1)}
                    id="prev-page"
                  >
                    ← Prev
                  </button>
                  <span className="text-mono text-muted" style={{ display: 'flex', alignItems: 'center', padding: '0 var(--space-md)' }}>
                    {page} / {pagination.pages}
                  </span>
                  <button
                    className="btn btn-ghost btn-sm"
                    disabled={page >= pagination.pages}
                    onClick={() => setPage(p => p + 1)}
                    id="next-page"
                  >
                    Next →
                  </button>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </>
  );
}
